server:
  port: 8081

spring:
  application:
    name: Microservice1
  config:
    enabled: true
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
