server:
  port: 8083

spring:
  application:
    name: Microservice-phoneBook
    config:
    enabled: true
    import: optional:configserver:http://localhost:8888
  openfeign:
  client:
    config:
      phoneBookMs:
        url: http://localhost:8083/pb/list
